name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      working-directory: ./backend
      run: go mod download

    - name: Test
      working-directory: ./backend
      run: go test ./... --cover -v -coverprofile=../coverage.out

    - name: Exec octocov action
      uses: k1LoW/octocov-action@v0
