name: Backend Test

on:
  pull_request:
    paths:
      - backend/**
  push:
    branches:
      - main

jobs:
  unit-and-e2e-test:
    name: Unit Test & E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: backend/go.sum
      - name: Test
        working-directory:
        run: |
          cp ./backend/.env.test ./backend/.env
          make test-cover
          mv ./backend/coverdir/merged/profile.txt ./coverage.out
      - name: Exec octocov action Merged
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.merged.yml
      - name: Move E2E Test Coverage
        run: |
          mv ./backend/coverdir/e2e/profile.txt ./coverage.out
      - name: Exec octocov action E2E Test
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.e2e.yml
      - name: Move Unit Test Coverage
        run: |
          mv ./backend/coverdir/unit/profile.txt ./coverage.out
      - name: Exec octocov action Unit Test
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.unit.yml
