name: Backend Test

on:
  pull_request:
    paths:
      - backend/**
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: backend/go.sum
      - name: Test
        run: |
          cp ./backend/.env.test ./backend/.env
          make test-cover-unit
          mv ./backend/cover.out ./coverage.out
      - name: Exec octocov action
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.unit.yml
  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: backend/go.sum
      - name: Test
        shell: bash
        run: |
          cp ./backend/.env.test ./backend/.env
          make test-cover-e2e
          mv ./backend/coverdir/e2e/profile.txt ./coverage.out
      - name: Exec octocov action
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.e2e.yml
  unit-and-e2e-test:
    name: Unit Test & E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: backend/go.sum
      - name: Test
        run: |
          cp ./backend/.env.test ./backend/.env
          make test-cover
          mv ./backend/coverdir/merged/profile.txt ./coverage.out
      - name: Exec octocov action Merged
        uses: yamoyamoto/octocov-action@v0
        with:
          config: .octocov.merged.yml

